name: our_foodie
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-238.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.5.0
  lottie: ^2.7.0
  flutter_riverpod: ^2.4.9
  flutter_polyline_points: ^2.0.0
  firebase_core: ^2.24.2
  firebase_database: ^10.3.8
  firebase_auth: ^4.15.3
  cloud_firestore:
  carousel_slider: ^4.2.1
  shared_preferences:
  fluttertoast: ^8.2.4
  intl: ^0.19.0
  image_picker: ^1.0.5
  flutter_rating_stars:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/animassets/mapanimation.json
    - assets/mapicons/
