name: our_foodie
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-238.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  google_maps_flutter_ios:
  google_maps_flutter:
  lottie:

  csc_picker:
  http:
  file_picker:
  path_provider:
  flutter_polyline_points:
  google_sign_in:
  geolocator:
  firebase_core:
  firebase_database:
  firebase_auth:
  cloud_firestore:
  carousel_slider:
  shared_preferences:
  fluttertoast:
  intl:

  flutter_rating_stars:
  url_launcher: ^6.2.6
  firebase_messaging: ^14.9.2
  mailer: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/animassets/mapanimation.json
    - assets/mapicons/
    - assets/states/states_and_cities.json
